export const MAX_WORD_LENGTH = 5
export const WORDS_LIST = [
"abats", "arabe", "abime","abris","acces","acide","acier","actes","admis","adore","adopt",
"aides","aigle","aimer","ainsi","aires","ajout","alerte","algue","alibi","alors",
"amour","amuse","anges","angle","anime","appel","apres","arbre","armes","arret",
"asile","assez","aucun","aussi","autre","avale","avant","avion","avoir","balle",
"banal","barre","bases","beaux","besoi","biais","biens","blanc","bleue","boire",
"boite","bonne","borde","bouch","boule","bruit","cable","cache","cadre","calme",
"campe","canal","capte","carre","carte","cause","celle","champ","chant","chaud",
"chefs","chien","chose","chute","cinqs","clair","claire","classe","clefs","coeur",
"coins","colle","comme","corps","cotee","coupe","court","couvre","craie","creux",
"crime","crois","cuire","cuite","cycle","danse","debut","dehors","delai","dents",
"depot","desir","dieux","digne","diner","diree","dises","donna","donne","doute",
"droit","duree","echec","ecran","ecrit","effet","egale","egard","elite","elles",
"email","emets","emmer","empli","encre","enfin","enjeu","entre","envoi","epais",
"epice","epine","epoux","equip","erres","essai","estom","etage","etais","etant",
"etatS","etape","etiez","etres","etude","evite","exact","exige","exile","extra",
"faces","facil","faits","faute","femme","ferme","fetes","feuil","fiere","filet",
"films","final","fines","fixes","flanc","flore","foire","fonds","force","forme",
"forts","fouet","foule","fours","foyer","frais","franc","frein","frere","fruit",
"fuite","gagne","garde","gazon","genre","germe","geste","gites","glace","gloire",
"gomme","gorge","gouge","goutt","gouts","grade","grain","grand","grape","grave",
"greve","grise","grosS","gueri","guide","habit","haine","halte","harpe","haute",
"herbe","heure","homme","honte","horde","hotel","huile","humain","image","imite",
"impot","index","indic","inter","irais","irait","issue","items","jalon","jambe",
"jauge","jaune","jeune","joint","jolie","jouer","jours","jugeS","jupes","juste",
"karma","kilos","kyste","label","lache","laits","lampe","lance","large","larme",
"laser","latin","laver","lecon","legal","leger","leurs","lieux","ligne","limbe",
"limon","lions","liste","litre","livre","local","loger","logis","loint","loirs",
"louer","loupe","lourd","loyal","luire","lundi","lutte","lycee","macro","magie",
"maire","maison","major","malin","malle","maman","mange","manie","manque","marie",
"marin","marre","masse","mateS","mater","matin","mauve","medal","media","merci",
"meres","merle","messe","metal","metre","metsS","meute","mieux","micro","mille",
"mince","mines","minor","minus","mises","mixte","mobile","modeS","model","moine",
"moins","moite","monde","monte","moral","morce","morts","motel","moule","moyen",
"muets","mural","musee","music","naive","nappe","naval","neant","nerfs","neufs",
"neige","nette","neveu","niche","niveau","noble","noeud","noire","norme","notes",
"nouer","noyau","nuage","nuire","nuits","objet","obten","occur","odeur","offre",
"ogive","ombre","oncle","ondes","ordre","organ","otage","ouest","outil","ouvre",
"pacte","pages","pains","paire","pales","palme","panel","panne","papes","parce",
"paris","parle","parmi","paroi","parte","parts","passe","pates","patin","pause",
"payer","paysS","peche","peine","pense","perdu","perle","perte","peser","peste",
"petit","phase","photo","piano","piece","pieds","pierre","pieux","piler","pilou",
"pince","pions","piste","pivot","place","plage","plais","plane","plante","platS",
"plein","pleur","pliée","plomb","pluie","poeme","poids","poing","point","poire",
"polar","polir","pomme","pontS","porte","poser","poste","potes","poule","pourr",
"pours","prend","presse","prets","prier","prime","prise","prive","probe","proie",
"prose","proue","prune","puits","pulpe","punit","quais","quand","quant","quart",
"quasi","quels","queue","quitt","quota","rabat","radio","rager","raide","rails",
"raire","ralle","rampe","range","rapide","rappel","rareS","raser","ratio","rayon",
"react","rebus","recit","recul","refus","regle","reine","reins","relie","remet",
"renal","rendu","rente","repas","repos","reput","reste","retro","reuni","reves",
"rider","roder", "rimer","rince","rions","risque","rital","rival","rives","robot",
"roche","roleS","roman","ronde","route","royal","ruche","ruine","rural","sable",
"sabre","sages","saine","saint","saisi","salir","salle","salon","salue","sangs",
"sante","saper","sauce","saule","sauts","sauve","savoir","scalp","scene","score",
"seche","secret","seize","selon","selle","semer","sente","serai","serre","serve",
"seuil","seule","seuls","sevir","sexis","siege","signe","singe","sinon","sirop",
"sirup","sites","situe","skate","slips","soeur","soins","soirs","solde",
"soles","somme","songe","sonne","sorte","soupe","sourc","souri","sousS","sport",
"stade","stage","stand","stars","stock","style","sucre","suite","suivi","super",
"suret","surfs","table","tache","taire","talon","tanks","taper","tapis","tarde",
"tarif","tarte","tasse","tauxS","taxer","teint","telS","tempe","tenir","tenue",
"terre","tests","texte","these","tiens","tient","tiger","tigre","tilde","tissu",
"titre","toile","tombe","tonne","torse","total","touche","tours","trace","train",
"trait","trame","trave","treve","triad","tribu","trier","trois","tronc","troue",
"trous","trust","tubes","tuile","tuner","turbo","tutor","ultra","union","unite",
"usine","utile","vache","vague","valet","valve","vapor","varie","vaste","veille",
"velos","vende","venir","vente","verbe","verre","versS","vertS","veste","veuve",
"viande","vices","video","vieux","vigne","villa","ville","vinyl","viole","virer",
"virus","viser","visse","vital","vitre","vivre","vocal","voeux","voici","voile",
"voire","voler","volte","votes","votre","voulu","voyez","wagon","yacht","zeste"
];

// Errors constants

export const WORD_TOO_LONG = "The word is above the maximum word length" 
export const WORD_NOT_IN_LIST = "The word is not in the list of valid words"